// ♠︎♣︎♥︎♦︎
//♤♧♡♢
//
const cards = [
	{name: 'A', val:1, suit: '♤'},
	{name: '2', val:2, suit: '♤'},
	{name: '3', val:3, suit: '♤'},
	{name: '4', val:4, suit: '♤'},
	{name: '5', val:5, suit: '♤'},
	{name: '6', val:6, suit: '♤'},
	{name: '7', val:7, suit: '♤'},
	{name: '8', val:8, suit: '♤'},
	{name: '9', val:9, suit: '♤'},
	{name: '10', val:10, suit: '♤'},
	{name: 'J', val:10, suit: '♤'},
	{name: 'Q', val:10, suit: '♤'},
	{name: 'K', val:0, suit: '♤'},
	{name: 'A', val:1, suit: '♡'},
	{name: '2', val:2, suit: '♡'},
	{name: '3', val:3, suit: '♡'},
	{name: '4', val:4, suit: '♡'},
	{name: '5', val:5, suit: '♡'},
	{name: '6', val:6, suit: '♡'},
	{name: '7', val:7, suit: '♡'},
	{name: '8', val:8, suit: '♡'},
	{name: '9', val:9, suit: '♡'},
	{name: '10', val:10, suit: '♡'},
	{name: 'J', val:10, suit: '♡'},
	{name: 'Q', val:10, suit: '♡'},
	{name: 'K', val:0, suit: '♡'},
	{name: 'A', val:1, suit: '♧'},
	{name: '2', val:2, suit: '♧'},
	{name: '3', val:3, suit: '♧'},
	{name: '4', val:4, suit: '♧'},
	{name: '5', val:5, suit: '♧'},
	{name: '6', val:6, suit: '♧'},
	{name: '7', val:7, suit: '♧'},
	{name: '8', val:8, suit: '♧'},
	{name: '9', val:9, suit: '♧'},
	{name: '10', val:10, suit: '♧'},
	{name: 'J', val:10, suit: '♧'},
	{name: 'Q', val:10, suit: '♧'},
	{name: 'K', val:0, suit: '♧'},
	{name: 'A', val:1, suit: '♢'},
	{name: '2', val:2, suit: '♢'},
	{name: '3', val:3, suit: '♢'},
	{name: '4', val:4, suit: '♢'},
	{name: '5', val:5, suit: '♢'},
	{name: '6', val:6, suit: '♢'},
	{name: '7', val:7, suit: '♢'},
	{name: '8', val:8, suit: '♢'},
	{name: '9', val:9, suit: '♢'},
	{name: '10', val:10, suit: '♢'},
	{name: 'J', val:10, suit: '♢'},
	{name: 'Q', val:10, suit: '♢'},
	{name: 'K', val:0, suit: '♢'},
	{name: 'Joker', val:-2, suit: null},
	{name: 'Joker', val:-2, suit: null},
]

export default cards