// ♠︎♣︎♥︎♦︎
//♤♧♡♢
//
const cards = [
	{name: 'A', val:1, suit: '♤', showing: false},
	{name: '2', val:2, suit: '♤', showing: false},
	{name: '3', val:3, suit: '♤', showing: false},
	{name: '4', val:4, suit: '♤', showing: false},
	{name: '5', val:5, suit: '♤', showing: false},
	{name: '6', val:6, suit: '♤', showing: false},
	{name: '7', val:7, suit: '♤', showing: false},
	{name: '8', val:8, suit: '♤', showing: false},
	{name: '9', val:9, suit: '♤', showing: false},
	{name: '10', val:10, suit: '♤', showing: false},
	{name: 'J', val:10, suit: '♤', showing: false},
	{name: 'Q', val:10, suit: '♤', showing: false},
	{name: 'K', val:0, suit: '♤', showing: false},
	{name: 'A', val:1, suit: '♡', showing: false},
	{name: '2', val:2, suit: '♡', showing: false},
	{name: '3', val:3, suit: '♡', showing: false},
	{name: '4', val:4, suit: '♡', showing: false},
	{name: '5', val:5, suit: '♡', showing: false},
	{name: '6', val:6, suit: '♡', showing: false},
	{name: '7', val:7, suit: '♡', showing: false},
	{name: '8', val:8, suit: '♡', showing: false},
	{name: '9', val:9, suit: '♡', showing: false},
	{name: '10', val:10, suit: '♡', showing: false},
	{name: 'J', val:10, suit: '♡', showing: false},
	{name: 'Q', val:10, suit: '♡', showing: false},
	{name: 'K', val:0, suit: '♡', showing: false},
	{name: 'A', val:1, suit: '♧', showing: false},
	{name: '2', val:2, suit: '♧', showing: false},
	{name: '3', val:3, suit: '♧', showing: false},
	{name: '4', val:4, suit: '♧', showing: false},
	{name: '5', val:5, suit: '♧', showing: false},
	{name: '6', val:6, suit: '♧', showing: false},
	{name: '7', val:7, suit: '♧', showing: false},
	{name: '8', val:8, suit: '♧', showing: false},
	{name: '9', val:9, suit: '♧', showing: false},
	{name: '10', val:10, suit: '♧', showing: false},
	{name: 'J', val:10, suit: '♧', showing: false},
	{name: 'Q', val:10, suit: '♧', showing: false},
	{name: 'K', val:0, suit: '♧', showing: false},
	{name: 'A', val:1, suit: '♢', showing: false},
	{name: '2', val:2, suit: '♢', showing: false},
	{name: '3', val:3, suit: '♢', showing: false},
	{name: '4', val:4, suit: '♢', showing: false},
	{name: '5', val:5, suit: '♢', showing: false},
	{name: '6', val:6, suit: '♢', showing: false},
	{name: '7', val:7, suit: '♢', showing: false},
	{name: '8', val:8, suit: '♢', showing: false},
	{name: '9', val:9, suit: '♢', showing: false},
	{name: '10', val:10, suit: '♢', showing: false},
	{name: 'J', val:10, suit: '♢', showing: false},
	{name: 'Q', val:10, suit: '♢', showing: false},
	{name: 'K', val:0, suit: '♢', showing: false},
	{name: 'Joker', val:-2, suit: null},
	{name: 'Joker', val:-2, suit: null},
]

export default cards